### ISSUE TITLE
JSCharset incorrectly detecting encoding

### ISSUE THREAD

**Issue by rprabhakaran-aptos-com** [danielgindi/node-autodetect-decoder-stream#4]
[Autodetect.txt](https://github.com/danielgindi/node-autodetect-decoder-stream/files/6294594/Autodetect.txt)

Team,

We noticed an issue with detecting character encoding and conversion of some specific string. (Eg., C’est). Some of these characters are not converted properly.

During investigation we found that issue is with jschardet package(1.*). When we tried the latest version jschardet package(2.3.0) it is working fine. It also requires refactor of Jschardet.Constants.MINIMUM_THRESHOLD based on below jschardet latest change.

https://github.com/aadsm/jschardet/commit/4ef274ba1efb2b2d82bda8dbc857179f732eec11#diff-8e3b187293d8e7902d08eff3c650466860fe527b0c7da8ec32c1ee4a450f97c5

Below are the usage of the same which requires refactoring:
- https://github.com/danielgindi/node-autodetect-decoder-stream/blob/master/index.js#L54
- https://github.com/danielgindi/node-autodetect-decoder-stream/blob/master/index.js#L77

Please help in fixing this.

**Comment by danielgindi** [comment]
Thanks! This actually removed the need for overriding Jschardet's constant to override the thresholds everytime.
